{{ range .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
type: Opaque
stringData:
  {{ range $key, $value := .secret }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
---
{{ end }}